data_params:
  batch_size: 16
  num_workers: 16
  augmentation_params:
    resize: 224

train_params:
  name: Unet3d_organ_26_06_SGD
# 3d_unet_ChannelAttention_flip_plus_shift_raq_FPN
#  model: models_zoo.segmentation.pspnet.PSPNet
  model: models_zoo.segmentation.unet.UNet
#  model: models_zoo.segmentation.unet3d.Modified3DUNet
  model_params: {
#    num_filters: 16
#    pretrained: False
    n_classes: 1}
  loss: losses.LossBinaryDice
  loss_params: {}
  metrics: [metrics.Dice]
  steps_per_epoch: 2500
  new_save: True
#  weights: ../weights/Unet3d_organ_23_06/0/tt_2_0.09316.pt
stages:
-
  load_best: False
  optimizer: SGD
  optimizer_params:
    lr: 0.0003
  scheduler: ReduceLROnPlateau
  scheduler_params:
    patience: 15
    factor: 0.5
    min_lr: 0.000001
    verbose: True
  epochs: 500
  augmentation: mix_transform
