data_params:
  batch_size: 32
  num_workers: 16
  augmentation_params: {
    pre_resize_size: 224,
    mix_hflip: 0.5,

  }


train_params:
  name: UNet
  model: models_zoo.segmentation.unet.UNet
  model_params: {
    upsampling: bilinear,
    n_channels: 1,
    n_classes: 1}
  loss: losses.LossBinaryDice
  loss_params: {}
  metrics: [metrics.Dice]
  steps_per_epoch: 2500
  new_save: True
#  weights: ../weights/Unet3d_organ_23_06/0/tt_2_0.09316.pt
stages:
-
  load_best: False
  optimizer: SGD
  optimizer_params:
    lr: 0.5
  scheduler: ReduceLROnPlateau
  scheduler_params:
    patience: 5
    factor: 0.5
    min_lr: 0.000001
    verbose: True
  epochs: 500
  augmentation: mix_transform
