data_params:
  batch_size: 18
  num_workers: 16
  augmentation_params:
    pre_resize_size: 288

train_params:
  name: segmentator_UNet_inference
  model: models_zoo.segmentation.unet.UNet
  model_params: {
    upsampling: bilinear,
    n_channels: 1,
    n_classes: 1}
  loss: losses.BCELoss2d
  loss_params: {}
  metrics: [losses.BCELoss2d]
  steps_per_epoch: 2500
  new_save: True
  weights: ../weights/UNet_augs/0/tt_1_0.18805.pt
stages:
-
  load_best: False
  optimizer: Adam
  optimizer_params:
    lr: 0.001
  scheduler: MultiStepLR
  scheduler_params:
    milestones: [ 0, 10, 20, 30]
    gamma: 0.7
  epochs: 300
  augmentation: mix_transform
