data_params:
  batch_size: 28
  num_workers: 64
  augmentation_params:
    resize: 512

train_params:
  name: densenet121_LBD #resnet.MultiResnet50_L_LBD_M_Dice
# 3d_unet_ChannelAttention_flip_plus_shift_raq_FPN
#  model: models_zoo.segmentation.pspnet.PSPNet
#  model: models_zoo.classification.resnet.resnet34
#  model: models_zoo.segmentation.resnet.MultiResnet50
  model: models_zoo.segmentation.densenet.MultiSEDensenet121
  model_params:
    num_filters: 16
    pretrained: True
    num_classes: 1
  loss: losses.LossBinaryDice  #losses.MixedLoss
  loss_params: {}
  metrics: [metrics.Dice]
  steps_per_epoch: 4000
  new_save: True
#  weights: ../weights/densenet121/0/tt_9_0.54119.pt
stages:
-
  load_best: False
  optimizer: Adam
  optimizer_params:
    lr: 0.0003    # 0.0003
  scheduler: ReduceLROnPlateau
  scheduler_params:
    mode: max
    patience: 10
    factor: 0.5
    min_lr: 0.00001
    verbose: True
  epochs: 750
  augmentation: mix_transform
