data_params:
  batch_size: 4
  num_workers: 64
  augmentation_params:
    resize: 512

train_params:
  name: densenet121_test
  model: models_zoo.segmentation.resnet.MultiResnet34 #models_zoo.segmentation.densenet.MultiSEDensenet121
  model_params:
    num_filters: 16
    pretrained: True
    num_classes: 1
  loss: losses.BCELoss2d
  loss_params: {}
  metrics: [losses.BCELoss2d]
  steps_per_epoch: 2500
  new_save: True
  weights: ../weights/MultiResnet34_LBD_10_08/0/tt_7_0.44000.pt #../weights/densenet121/0/tt_9_0.54119.pt
stages:
-
  load_best: False
  optimizer: Adam
  optimizer_params:
    lr: 0.001
  scheduler: MultiStepLR
  scheduler_params:
    milestones: [ 0, 10, 20, 30]
    gamma: 0.7
  epochs: 300
  augmentation: test_transform
