data_params:
  batch_size: 4
  num_workers: 64
  augmentation_params:
    resize: 1024

train_params:
  name: EfficientNet_classification_ok #resnet.MultiResnet50_L_LBD_M_Dice
# 3d_unet_ChannelAttention_flip_plus_shift_raq_FPN
#  model: models_zoo.segmentation.pspnet.PSPNet
#  model: models_zoo.classification.resnet.resnet34
#  model: models_zoo.segmentation.resnet.MultiResnet50
  model: models_zoo.classification.resnet.EfficientNet_1class #.se_resnet.se_resnext50
  model_params: {
  }
    #num_classes: 1 } #,
   # pretrained: True

#    num_filters: 16
#    n_classes: 1}
# loss: losses.BCE

  loss: losses.BCE
  loss_params: {}
  metrics: [metrics.Binary_Accuracy]
  steps_per_epoch: 2500
  new_save: True
#  weights: ../weights/Unet3d_organ_23_06/0/tt_2_0.09316.pt
stages:
-
  load_best: False
  optimizer: Adam
  optimizer_params:
    lr: 0.0003
  scheduler: ReduceLROnPlateau
  scheduler_params:
    patience: 7
    factor: 0.5
    min_lr: 0.000001
    verbose: True
  epochs: 750
  augmentation: mix_transform
