dumps:
  path: ../weights/MultiResnet34_LBD_10_08/0/tt_7_0.44000.pt #../weights/densenet121/0/tt_9_0.54119.pt   # path to weights dir
  weights: weights                  # name of weights dir
  logs: logs                        # name of logs dir
  name_save: tt                     # name to save models

data:
  path: ../../../../raid/data/ibespalov/SIIM_ACR/test_samples #train_samples # path to data directory
  train_images: ./   # dir to train images
  train_masks: ./    # dir to labels
  test_images: ../submission.csv #../train_segmentation_view.csv # dir to test
  folds: ../submission.csv #../train_segmentation_view.csv    # validation folds
  predictions_path: preds.csv # predictions name